### ISSUE TITLE
NoneType errors caused by potential bugs in analysis.py (in Python 3.8.3)

### ISSUE THREAD

**Issue by EvanXiaa** [Aurore54F/syntactic-jsdetector#1]
Hey Aurore,

When I was running this code I noticed that you declared a global variable **features2int_dict** in analysis.py and further used it in a child process which runs **worker_get_features_vector**. However, the child process could not recognize this variable and resulted in a NoneType error.

The potential buggy code 

```
 try:

                features = features_space.features_vector(analysis.file_path,
                                                          len(features2int_dict), features2int_dict)
                analysis.set_features(features)
                out_queue.put(analysis)  # To share modified analysis object between processes
```
and the error message is

> object of type 'NoneType' has no len()

I pass features2int_dict as an argument of **worker_get_features_vector** to help it work again. And it solves the problem.

**Comment by Aurore54F** [comment]
Hi Yifan,

That's weird, I mean it definitely used to work.
Someone reported the exact [same issue for JStap](https://github.com/Aurore54F/JStap/issues/3) but apparently importing my functions from another python script solved the problem for them.

Is it possible that your fix only works when you run this tool with a single process?

**Comment by EvanXiaa** [comment]
> Hi Yifan,
> 
> That's weird, I mean it definitely used to work. Someone reported the exact [same issue for JStap](https://github.com/Aurore54F/JStap/issues/3) but apparently importing my functions from another python script solved the problem for them.
> 
> Is it possible that your fix only works when you run this tool with a single process?

Well, I'm not sure if it is related to specific python version. I just followed the instruction in readme and ran 

`$ python3 src/learner.py --d  BENIGN MALICIOUS --l benign malicious --vd BENIGN-VALIDATE MALICIOUS-VALIDATE --vl benign malicious --clf BNB --mn MODEL-NAME --md MODEL-DIR`

Unfortunately It does not work and throws a NoneType error. 

> Is it possible that your fix only works when you run this tool with a single process?

After my fix the origin command works well, which uses 2 processes. (I modified the function  worker_get_features_vector and added  features2int_dict to its arguments list to ensure the variable could be passed successfully when invoked with Process())

**Comment by Aurore54F** [comment]
I just downloaded the repo and tried your command, and it's working just fine for me.

To be sure we are on the same page:
- BENIGN: path of the directory containing benign JS files, to train the model;
- MALICIOUS: path of the directory containing malicious JS files, to train the model;
- benign / malicious: the ground-truth labels corresponding to the directories (1 label per dir);
- BENIGN-VALIDATE: path of the directory containing benign JS files, to validate the model;
- MALICIOUS-VALIDATE: path of the directory containing malicious JS files, to validate the model;
- benign / malicious: the ground-truth labels corresponding to the directories (1 label per dir);
- MODEL-NAME / MODEL-DIR: your chosen name for the model and the path where it will be stored.

Is this also your setting?

**Comment by EvanXiaa** [comment]
Yes, I just run the same command with Python3.8.3. 
(For simplification, my benign/malicious directory is same as benign-validate/malicious-validate.)
Here is the complete terminal log. Notice that I didn't modify any part of the code. I hope it could help)

> ➜  detector mkdir evaluate
> ➜  detector cd evaluate 
> ➜  evaluate git clone git@github.com:Aurore54F/syntactic-jsdetector.git
> Cloning into 'syntactic-jsdetector'...
> remote: Enumerating objects: 26, done.
> remote: Counting objects: 100% (7/7), done.
> remote: Compressing objects: 100% (5/5), done.
> remote: Total 26 (delta 0), reused 7 (delta 0), pack-reused 19
> Receiving objects: 100% (26/26), 34.59 KiB | 138.00 KiB/s, done.
> Resolving deltas: 100% (2/2), done.
> ➜  evaluate cd syntactic-jsdetector 
> ➜  syntactic-jsdetector git:(master) ls
> LICENSE          README.md        requirements.txt src
> ➜  syntactic-jsdetector git:(master) python3 src/learner.py --d /Users/xiayifan/WebstormProjects/wasm/detector/demo_suite/benign /Users/xiayifan/WebstormProjects/wasm/detec
> tor/demo_suite/malicious --l benign malicious --vd /Users/xiayifan/WebstormProjects/wasm/detector/demo_suite/benign /Users/xiayifan/WebstormProjects/wasm/detector/demo_suite/malicious --vl benign malicious --clf BNB --mn MODEL-NAME --md ./       
> Currently handling /Users/xiayifan/WebstormProjects/wasm/detector/demo_suite/benign
> Currently handling /Users/xiayifan/WebstormProjects/wasm/detector/demo_suite/malicious
> Currently selecting the features with chi2
> ERROR:Something went wrong with /Users/xiayifan/WebstormProjects/wasm/detector/demo_suite/benign/10328.js
> object of type 'NoneType' has no len()
> ERROR:Something went wrong with /Users/xiayifan/WebstormProjects/wasm/detector/demo_suite/benign/1022.js
> object of type 'NoneType' has no len()
> ERROR:Something went wrong with /Users/xiayifan/WebstormProjects/wasm/detector/demo_suite/benign/8088.js
> object of type 'NoneType' has no len()
> ERROR:Something went wrong with /Users/xiayifan/WebstormProjects/wasm/detector/demo_suite/benign/8218.js
> object of type 'NoneType' has no len()
> ERROR:Something went wrong with /Users/xiayifan/WebstormProjects/wasm/detector/demo_suite/benign/9193.js
> object of type 'NoneType' has no len()
> ERROR:Something went wrong with /Users/xiayifan/WebstormProjects/wasm/detector/demo_suite/benign/1989.js
> object of type 'NoneType' has no len()
> ERROR:Something went wrong with /Users/xiayifan/WebstormProjects/wasm/detector/demo_suite/benign/6388.js
> object of type 'NoneType' has no len()
> ERROR:Something went wrong with /Users/xiayifan/WebstormProjects/wasm/detector/demo_suite/benign/6551.js
> object of type 'NoneType' has no len()
> ERROR:Something went wrong with /Users/xiayifan/WebstormProjects/wasm/detector/demo_suite/benign/4941.js
> object of type 'NoneType' has no len()
> ERROR:Something went wrong with /Users/xiayifan/WebstormProjects/wasm/detector/demo_suite/benign/9192.js
> object of type 'NoneType' has no len()
> ERROR:Something went wrong with /Users/xiayifan/WebstormProjects/wasm/detector/demo_suite/benign/7016.js
> object of type 'NoneType' has no len()
> ERROR:Something went wrong with /Users/xiayifan/WebstormProjects/wasm/detector/demo_suite/benign/88.js
> object of type 'NoneType' has no len()
> ERROR:Something went wrong with /Users/xiayifan/WebstormProjects/wasm/detector/demo_suite/benign/2883.js
> object of type 'NoneType' has no len()
> ERROR:Something went wrong with /Users/xiayifan/WebstormProjects/wasm/detector/demo_suite/benign/98.js
> object of type 'NoneType' has no len()
> ERROR:Something went wrong with /Users/xiayifan/WebstormProjects/wasm/detector/demo_suite/benign/10725.js
> object of type 'NoneType' has no len()
> ERROR:Something went wrong with /Users/xiayifan/WebstormProjects/wasm/detector/demo_suite/benign/1221.js
> object of type 'NoneType' has no len()
> ERROR:Something went wrong with /Users/xiayifan/WebstormProjects/wasm/detector/demo_suite/benign/10189.js
> object of type 'NoneType' has no len()
> ERROR:Something went wrong with /Users/xiayifan/WebstormProjects/wasm/detector/demo_suite/benign/6626.js
> object of type 'NoneType' has no len()
> ERROR:Something went wrong with /Users/xiayifan/WebstormProjects/wasm/detector/demo_suite/benign/6742.js
> object of type 'NoneType' has no len()
> ERROR:Something went wrong with /Users/xiayifan/WebstormProjects/wasm/detector/demo_suite/benign/10380.js
> object of type 'NoneType' has no len()
> ERROR:Something went wrong with /Users/xiayifan/WebstormProjects/wasm/detector/demo_suite/benign/3622.js
> object of type 'NoneType' has no len()
> ERROR:Something went wrong with /Users/xiayifan/WebstormProjects/wasm/detector/demo_suite/benign/8101.js
> object of type 'NoneType' has no len()
> ERROR:Something went wrong with /Users/xiayifan/WebstormProjects/wasm/detector/demo_suite/benign/10579.js
> object of type 'NoneType' has no len()
> ERROR:Something went wrong with /Users/xiayifan/WebstormProjects/wasm/detector/demo_suite/benign/5716.js
> object of type 'NoneType' has no len()
> ERROR:Something went wrong with /Users/xiayifan/WebstormProjects/wasm/detector/demo_suite/benign/3570.js
> object of type 'NoneType' has no len()
> ERROR:Something went wrong with /Users/xiayifan/WebstormProjects/wasm/detector/demo_suite/benign/7677.js
> object of type 'NoneType' has no len()
> ERROR:Something went wrong with /Users/xiayifan/WebstormProjects/wasm/detector/demo_suite/benign/5882.js
> object of type 'NoneType' has no len()
> ERROR:Something went wrong with /Users/xiayifan/WebstormProjects/wasm/detector/demo_suite/benign/5441.js
> object of type 'NoneType' has no len()
> ERROR:Something went wrong with /Users/xiayifan/WebstormProjects/wasm/detector/demo_suite/benign/9417.js
> object of type 'NoneType' has no len()
> ERROR:Something went wrong with /Users/xiayifan/WebstormProjects/wasm/detector/demo_suite/benign/4036.js
> object of type 'NoneType' has no len()
> ERROR:Something went wrong with /Users/xiayifan/WebstormProjects/wasm/detector/demo_suite/benign/9594.js
> object of type 'NoneType' has no len()
> ERROR:Something went wrong with /Users/xiayifan/WebstormProjects/wasm/detector/demo_suite/benign/10140.js
> object of type 'NoneType' has no len()
> ERROR:Something went wrong with /Users/xiayifan/WebstormProjects/wasm/detector/demo_suite/benign/7663.js
> object of type 'NoneType' has no len()
> ERROR:Something went wrong with /Users/xiayifan/WebstormProjects/wasm/detector/demo_suite/benign/10939.js
> object of type 'NoneType' has no len()
> ERROR:Something went wrong with /Users/xiayifan/WebstormProjects/wasm/detector/demo_suite/benign/13620.js
> object of type 'NoneType' has no len()
> ERROR:Something went wrong with /Users/xiayifan/WebstormProjects/wasm/detector/demo_suite/benign/1731.js
> object of type 'NoneType' has no len()
> ERROR:Something went wrong with /Users/xiayifan/WebstormProjects/wasm/detector/demo_suite/benign/6409.js
> object of type 'NoneType' has no len()
> ERROR:Something went wrong with /Users/xiayifan/WebstormProjects/wasm/detector/demo_suite/benign/8989.js
> object of type 'NoneType' has no len()
> ERROR:Something went wrong with /Users/xiayifan/WebstormProjects/wasm/detector/demo_suite/benign/2317.js
> object of type 'NoneType' has no len()
> ERROR:Something went wrong with /Users/xiayifan/WebstormProjects/wasm/detector/demo_suite/benign/3913.js
> object of type 'NoneType' has no len()
> ERROR:Something went wrong with /Users/xiayifan/WebstormProjects/wasm/detector/demo_suite/benign/4312.js
> object of type 'NoneType' has no len()
> ERROR:Something went wrong with /Users/xiayifan/WebstormProjects/wasm/detector/demo_suite/benign/2055.js
> object of type 'NoneType' has no len()
> ERROR:Something went wrong with /Users/xiayifan/WebstormProjects/wasm/detector/demo_suite/benign/1843.js
> object of type 'NoneType' has no len()
> ERROR:Something went wrong with /Users/xiayifan/WebstormProjects/wasm/detector/demo_suite/benign/10779.js
> object of type 'NoneType' has no len()
> ERROR:Something went wrong with /Users/xiayifan/WebstormProjects/wasm/detector/demo_suite/benign/11444.js
> object of type 'NoneType' has no len()
> ERROR:Something went wrong with /Users/xiayifan/WebstormProjects/wasm/detector/demo_suite/benign/664.js
> object of type 'NoneType' has no len()
> ERROR:Something went wrong with /Users/xiayifan/WebstormProjects/wasm/detector/demo_suite/benign/2083.js
> object of type 'NoneType' has no len()
> ERROR:Something went wrong with /Users/xiayifan/WebstormProjects/wasm/detector/demo_suite/benign/10127.js
> object of type 'NoneType' has no len()
> ERROR:Something went wrong with /Users/xiayifan/WebstormProjects/wasm/detector/demo_suite/benign/11574.js
> object of type 'NoneType' has no len()
> ERROR:Something went wrong with /Users/xiayifan/WebstormProjects/wasm/detector/demo_suite/benign/3967.js
> object of type 'NoneType' has no len()
> ERROR:Something went wrong with /Users/xiayifan/WebstormProjects/wasm/detector/demo_suite/benign/7447.js
> object of type 'NoneType' has no len()
> ERROR:Something went wrong with /Users/xiayifan/WebstormProjects/wasm/detector/demo_suite/benign/6828.js
> object of type 'NoneType' has no len()
> ERROR:Something went wrong with /Users/xiayifan/WebstormProjects/wasm/detector/demo_suite/benign/6879.js
> object of type 'NoneType' has no len()
> ERROR:Something went wrong with /Users/xiayifan/WebstormProjects/wasm/detector/demo_suite/benign/12103.js
> object of type 'NoneType' has no len()
> ERROR:Something went wrong with /Users/xiayifan/WebstormProjects/wasm/detector/demo_suite/benign/1823.js
> object of type 'NoneType' has no len()
> ERROR:Something went wrong with /Users/xiayifan/WebstormProjects/wasm/detector/demo_suite/benign/2798.js
> object of type 'NoneType' has no len()
> ERROR:Something went wrong with /Users/xiayifan/WebstormProjects/wasm/detector/demo_suite/benign/3407.js
> object of type 'NoneType' has no len()
> ERROR:Something went wrong with /Users/xiayifan/WebstormProjects/wasm/detector/demo_suite/benign/6174.js
> object of type 'NoneType' has no len()
> ERROR:Something went wrong with /Users/xiayifan/WebstormProjects/wasm/detector/demo_suite/benign/8244.js
> object of type 'NoneType' has no len()
> ERROR:Something went wrong with /Users/xiayifan/WebstormProjects/wasm/detector/demo_suite/benign/11320.js
> object of type 'NoneType' has no len()
> ERROR:Something went wrong with /Users/xiayifan/WebstormProjects/wasm/detector/demo_suite/benign/4219.js
> object of type 'NoneType' has no len()
> ERROR:Something went wrong with /Users/xiayifan/WebstormProjects/wasm/detector/demo_suite/benign/3376.js
> object of type 'NoneType' has no len()
> ERROR:Something went wrong with /Users/xiayifan/WebstormProjects/wasm/detector/demo_suite/benign/5979.js
> object of type 'NoneType' has no len()
> ERROR:Something went wrong with /Users/xiayifan/WebstormProjects/wasm/detector/demo_suite/benign/4751.js
> object of type 'NoneType' has no len()
> ERROR:Something went wrong with /Users/xiayifan/WebstormProjects/wasm/detector/demo_suite/benign/3939.js
> object of type 'NoneType' has no len()
> ERROR:Something went wrong with /Users/xiayifan/WebstormProjects/wasm/detector/demo_suite/benign/9026.js
> object of type 'NoneType' has no len()
> ERROR:Something went wrong with /Users/xiayifan/WebstormProjects/wasm/detector/demo_suite/benign/10920.js
> object of type 'NoneType' has no len()
> ERROR:Something went wrong with /Users/xiayifan/WebstormProjects/wasm/detector/demo_suite/benign/10623.js
> object of type 'NoneType' has no len()
> ERROR:Something went wrong with /Users/xiayifan/WebstormProjects/wasm/detector/demo_suite/benign/2546.js
> object of type 'NoneType' has no len()
> ERROR:Something went wrong with /Users/xiayifan/WebstormProjects/wasm/detector/demo_suite/benign/4980.js
> object of type 'NoneType' has no len()
> ERROR:Something went wrong with /Users/xiayifan/WebstormProjects/wasm/detector/demo_suite/benign/8460.js
> object of type 'NoneType' has no len()
> ERROR:Something went wrong with /Users/xiayifan/WebstormProjects/wasm/detector/demo_suite/benign/3699.js
> object of type 'NoneType' has no len()
> ERROR:Something went wrong with /Users/xiayifan/WebstormProjects/wasm/detector/demo_suite/benign/9221.js
> object of type 'NoneType' has no len()
> ERROR:Something went wrong with /Users/xiayifan/WebstormProjects/wasm/detector/demo_suite/benign/8415.js
> object of type 'NoneType' has no len()
> ERROR:Something went wrong with /Users/xiayifan/WebstormProjects/wasm/detector/demo_suite/benign/1316.js
> object of type 'NoneType' has no len()
> ERROR:Something went wrong with /Users/xiayifan/WebstormProjects/wasm/detector/demo_suite/benign/5509.js
> object of type 'NoneType' has no len()
> ERROR:Something went wrong with /Users/xiayifan/WebstormProjects/wasm/detector/demo_suite/benign/10515.js
> object of type 'NoneType' has no len()
> ERROR:Something went wrong with /Users/xiayifan/WebstormProjects/wasm/detector/demo_suite/benign/9351.js
> object of type 'NoneType' has no len()
> ERROR:Something went wrong with /Users/xiayifan/WebstormProjects/wasm/detector/demo_suite/benign/5459.js
> object of type 'NoneType' has no len()
> ERROR:Something went wrong with /Users/xiayifan/WebstormProjects/wasm/detector/demo_suite/benign/207.js
> object of type 'NoneType' has no len()
> ERROR:Something went wrong with /Users/xiayifan/WebstormProjects/wasm/detector/demo_suite/malicious/883466bb4e7a2c1af60d45663e2aabbae1d287835ce77b812267dd1d3915f304.js
> object of type 'NoneType' has no len()
> ERROR:Something went wrong with /Users/xiayifan/WebstormProjects/wasm/detector/demo_suite/malicious/163ac0682e7ba1ba6b2ca78bd3ac6a09e9abd887f0dd61ba26dca4852d20b41b.js
> object of type 'NoneType' has no len()
> ERROR:Something went wrong with /Users/xiayifan/WebstormProjects/wasm/detector/demo_suite/malicious/46a88039f4a3858c3ce3486a16ef9f42b1bc914426024fcf980253f98d990a4a.js
> object of type 'NoneType' has no len()
> ERROR:Something went wrong with /Users/xiayifan/WebstormProjects/wasm/detector/demo_suite/malicious/458d142b1cbd60829ad351f9ffeea18084600cbba63b7182b24922593ee1feda.js
> object of type 'NoneType' has no len()
> ERROR:Something went wrong with /Users/xiayifan/WebstormProjects/wasm/detector/demo_suite/malicious/eda05373b202bc09ed1215238bbe430d35f548124af02b3f547b4d317d8d2f36.js
> object of type 'NoneType' has no len()
> ERROR:Something went wrong with /Users/xiayifan/WebstormProjects/wasm/detector/demo_suite/malicious/ac2a86b100aa20de9f746aaf49f13dd59805ea21632cb9cb4a998daa33791966.js
> object of type 'NoneType' has no len()
> ERROR:Something went wrong with /Users/xiayifan/WebstormProjects/wasm/detector/demo_suite/malicious/9ec5965be8890f1ffa84ab02cb8fd953801e8e6a157f3bc5c2af0d33500ad610.js
> object of type 'NoneType' has no len()
> ERROR:Something went wrong with /Users/xiayifan/WebstormProjects/wasm/detector/demo_suite/malicious/861352c62e2b507959ce10da59295ebe010753e4f40c7a943f7449e507b84c4c.js
> object of type 'NoneType' has no len()
> ERROR:Something went wrong with /Users/xiayifan/WebstormProjects/wasm/detector/demo_suite/malicious/ca342e0a8604840218a47edb3834c907bb9b0443dcbdfc92245431812ea4f16d.js
> object of type 'NoneType' has no len()
> ERROR:Something went wrong with /Users/xiayifan/WebstormProjects/wasm/detector/demo_suite/malicious/75e3c3b4e92f6204e369e3db2c27abc6cb30bc09a1a64c3279c71ec049242d57.js
> object of type 'NoneType' has no len()
> ERROR:Something went wrong with /Users/xiayifan/WebstormProjects/wasm/detector/demo_suite/malicious/4c81659d0603b8f4256642c9cb5f21cc6b95e97dd025c0d83ad53ef597e0e8b6.js
> object of type 'NoneType' has no len()
> ERROR:Something went wrong with /Users/xiayifan/WebstormProjects/wasm/detector/demo_suite/malicious/8d71f9df669d0fb3d22cfb2c3b78fe992f4e1995fd67cf3cdb41f74df14f3b13.js
> object of type 'NoneType' has no len()
> ERROR:Something went wrong with /Users/xiayifan/WebstormProjects/wasm/detector/demo_suite/malicious/b3886956337dea5a25140f5ee8e51a57ad80403eb3a9a300deb2e165d35dfbb5.js
> object of type 'NoneType' has no len()
> ERROR:Something went wrong with /Users/xiayifan/WebstormProjects/wasm/detector/demo_suite/malicious/cfa4a53c1ee101b7977abc971c63cb14e3867e24d284f55602e06ce3ebc99264.js
> object of type 'NoneType' has no len()
> ERROR:Something went wrong with /Users/xiayifan/WebstormProjects/wasm/detector/demo_suite/malicious/84b9a6867266ae4a609192db6476a27b8764820bea427fbce667cbe957922c46.js
> object of type 'NoneType' has no len()
> ERROR:Something went wrong with /Users/xiayifan/WebstormProjects/wasm/detector/demo_suite/malicious/5620a3cc882af824c944d671490d91b233bd29b484316ea8c971288ee6bef55f.js
> object of type 'NoneType' has no len()
> ERROR:Something went wrong with /Users/xiayifan/WebstormProjects/wasm/detector/demo_suite/malicious/2e8948d85edd97746b1f39c9315e0ca4f45c64c3e7606264b9b377f88b019231.js
> object of type 'NoneType' has no len()
> ERROR:Something went wrong with /Users/xiayifan/WebstormProjects/wasm/detector/demo_suite/malicious/1585ecad6203759d543932d04b76d7a6c0daf1d076c934312645b47841981883.js
> object of type 'NoneType' has no len()
> ERROR:Something went wrong with /Users/xiayifan/WebstormProjects/wasm/detector/demo_suite/malicious/a6d5eb02ff8e612162d40c9f54eeee6367f500d6dd9919320b2c2651800617fc.js
> object of type 'NoneType' has no len()
> Traceback (most recent call last):
>   File "src/learner.py", line 209, in <module>
>     main_learn()
>   File "src/learner.py", line 195, in main_learn
>     analysis.main_analysis(js_dirs=js_dirs, labels_dirs=labels_d,
>   File "/Users/xiayifan/WebstormProjects/wasm/detector/evaluate/syntactic-jsdetector/src/analysis.py", line 110, in main_analysis
>     features_repr = get_features_representation(analyses)
>   File "/Users/xiayifan/WebstormProjects/wasm/detector/evaluate/syntactic-jsdetector/src/analysis.py", line 255, in get_features_representation
>     if len(tab_res[0]) != tab_res[1].shape[0] or len(tab_res[0]) != len(tab_res[2])\
> AttributeError: 'NoneType' object has no attribute 'shape'

**Comment by Aurore54F** [comment]
Thank you for the extra info. I'm not sure how to help you since I cannot reproduce the issue.
To double check: have you installed Esprima? And have you tried running the code on just 1 file (like write 2 lines of JS) and pass this file as input everywhere; I'm wondering if your inputs could be a problem. Honestly, I'm confused by the error log.

**Comment by EvanXiaa** [comment]
Thank you for your kind help. 
I think I have check the environment on my PC and it satisfies the requirements. I did run the code with 1 file and it resulted in same issue. 
However, with simple modification as I mentioned, the code works quite well. Maybe it could only happen in some special environment. :-)
Anyhow, thank you so much for replying!
